[package]
name = "flo-protocol"
version = "0.2.0"
authors = ["pfried <philipsfried@gmail.com>"]

[dependencies]
flo-event = { path = "../flo-event" }
log = "0.3"
nom = "2.2.1"
byteorder = "1"
chrono = "^0.2"
rand = "0.3"

